{% set name = "conda-content-trust" %}
{% set version = "0.3.2" %}
{% set sha256 = "6d459ca40d3775220ad7a2886a7c367a0d966b47cc0b97f27fb6be0439e361c9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://github.com/conda/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli

requirements:
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python
    - conda >=26.3.0
    - cryptography >=41

test:
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  requires:
    - pip
  commands:
    - pip check
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md
